name: Publish Docker image
on:
  workflow_dispatch:
    tags:
      description: "Manual build push"
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          file: ./Dockerfile.miniconda3
          # repository: russtorres/flatbuffers_miniconda_docker
          tags: |
            russtorres/flatbuffers_miniconda_docker:latest
            russtorres/flatbuffers_miniconda_docker:miniconda3
          # tag_with_ref: true
